language: objective-c
osx_image: xcode9.2

script:
- xcodebuild clean build -project BinarySwift.xcodeproj -scheme BinarySwift_OSX
- xcodebuild test -project BinarySwift.xcodeproj -scheme BinarySwiftTests_OSX
